server:
  port: 8082

servers:
  ribbon:
    listOfServers: example.com, google.com
ribbon:
  eureka:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: eureka-client-ribbon-alone
